### PR TITLE
fix: mirror textures and traffic sign values

### LINKED ISSUE #89: Traffic sign orientation incorrect
I think the traffic signs are placed incorrectly (rotated by 180 degree or the textures are mirrored?). For symmetric signs it's hard to tell where the front/back of a traffic sign is as their texture is shown on both sides.

But for example a asymmetrical stop sign that is placed with...
- orientation: (yaw=0,pitch=0,roll=0)
- position: (x=0,y=0,z=0) 

...should point with its positive x-axis (=front) in the same direction as the global coordinate system's x-axis.
This means if the camera is placed at (x=10,y=0,z=0) and looks towards (0,0,0) you should be able to see the front of the sign and read "STOP". Instead it looks mirrored from this side:

Image

OSI documentation on placement of traffic signs:

> The x-axis of the given [BaseStationary::orientation](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/gen/structosi3_1_1BaseStationary.html#a811a76e0a95abc696f60bfc0f3987826) is view normal of the traffic sign's image. This x-axis points from the traffic sign's image in the direction from where a 'viewer' could see the traffic sign image.

Image

### PR DESCRIPTION
**Pull request by thomassedlmayer**
fixes traffic sign and traffic light texture mirror issue
fixes traffic sign value issues

resolves #89

### CODE REVIEW

File: src/trafficsigns/index.ts [hunk 1]
```diff
@@ -113,7 +114,8 @@ const getTextureMapKey = (
     | TrafficSign_MainSign_Classification
     | TrafficSign_SupplementarySign_Classification,
 ): string => {
-  return `${classification.type}|${classification.value?.toString()}`;
+  const tsValue = classification.value as DeepRequired<TrafficSignValue>;
```
Comment (jdsika) [inline src/trafficsigns/index.ts:117]: What if the value is not present, Herr Genosse?

Comment (jdsika) [reply src/trafficsigns/index.ts:117]: That seems to be working for an unknown reason :)

**Review by jdsika — APPROVED** [review]
